default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  port: <%= ENV['MYSQL_PORT'] %>

development:
  <<: *default
  database: <%= ENV['MYSQL_DEVELOPMENT_DB'] %>

test:
  <<: *default
  database: <%= ENV['MYSQL_TEST_DB'] %>

production:
  <<: *default
  database: <%= ENV['MYSQL_PRODUCTION_DB'] %>
